apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-mapper
data:
  configData: |
    grpc_server:
      socket_path: /etc/kubeedge/temperature-sensor-mapper.sock
    common:
      name: Temperature-Sensor-Mapper-mapper
      version: v1.13.0
      api_version: v1.0.0
      protocol: modbus   # TODO add your protocol name
      address: 0.0.0.0
      edgecore_sock: /etc/kubeedge/dmi.sock
