apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperature-sensor-mapper
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      nodeName: kind-worker # 1.replace with your edge node name
      containers:
        - name: demo
          volumeMounts: # Required, mapper need to communicate with grpcclient and get the config
            - name: test-volume
              mountPath: /etc/kubeedge
            - name: config
              mountPath: /tmp
          # env: # Not Required, this field is used to mount the user database key
          #   - name: TOKEN
          #     valueFrom:
          #       secretKeyRef:
          #         name: mysecret
          #         key: token
          image: aaqwqaa/temperature-mapper:v1.0 # 2.Replace with your mapper image name
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 300m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          command: [ "bash","-c" ]
          args: [ "/kubeedge/main --config-file /tmp/config.yaml --v 5" ] 
      volumes:
        - name: test-volume
          hostPath:
            path: /etc/kubeedge
            type: Directory
        - name: config
          configMap:
            name: cm-mapper
            items:
              - key: configData
                path: config.yaml



---
# 添加 Service 配置 暴露端口
apiVersion: v1
kind: Service
metadata:
  name: mapper-service
spec:
  type: NodePort
  selector:
    app: demo
  ports:
    - name: http
      protocol: TCP
      port: 7777           # Service 的虚拟端口
      targetPort: 7777   # 容器端口
      nodePort: 30077    # 节点暴露的端口（可选范围 30000-32767）
    - name: mqtt
      protocol: TCP
      port: 1883           
      targetPort: 1883   
      nodePort: 31883   
