apiVersion: devices.kubeedge.io/v1beta1
kind: Device
metadata:
  name: temperature-instance

spec:
  deviceModelRef:
    name: temperature-model
  # 协议
  protocol:
    protocolName: modbus
    configData:
      communicateMode: "TCP"   #TCP/RTU
      port: "5502"             # replace the port with your modbus device port
      slaveID: 1
      ip: "127.0.0.1"   # 1.replace the ip with your modbus device ip
  nodeName: "kind-worker" # 2.replace the nodeName with your edge node name
  #属性
  properties:
    - name: temperature
      visitors:
        protocolName: modbus
        configData:
          dataType: "float"  #Enum::int/float/double/string/boolean/bytes
          register: "HoldingRegister"
          offset: 0  # 寄存器的偏移量
          limit: 1   # 读取寄存器的数量
          scale: 0.1 # 温度值的缩放因子
          isSwap: false  # 不交换字节
          isRegisterSwap: false # 不交换寄存器
          max: 100.0
          min: 1.0
      collectCycle: 10000
      reportCycle: 10000
      reportToCloud: true
      # 开启推送功能需要部署相关的服务,如mosquitto broker
      pushMethod:
        mqtt:
          topic: "current temperature"
          qos: 0
          address: "tcp://172.18.0.3:31883"  # replace the address with your mqtt broker address
          retained: false
    - name: status
      collectCycle: 10000
      reportCycle: 10000
      reportToCloud: true
      desired:
        value: "1"
      visitors:
        protocolName: modbus
        configData:
          dataType: "int"
          register: "CoilRegister"
          offset: 0
          limit: 1
          scale: 1
          isSwap: false
          isRegisterSwap: false
  #方法,可自定义
  methods:
    - name: UpdateStatus
      description: update the status of the device
      propertyNames:
        - status
    - name: UpdateTemperature
      description: update the temperature of the device
      propertyNames:
        - temperature
status:
  twins:
    - propertyName: temperature
      reported:
        metadata:
          timestamp: "1688663400"
          type: "float"
        value: "25.5"
      observedDesired:
        metadata:
          timestamp: "1688663400"
          type: "float"
        value: "25.5"
    - propertyName: status
      reported:
        metadata:
          timestamp: "1688663400"
          type: "int"
        value: "1"
      observedDesired:
        metadata:
          timestamp: "1688663400"
          type: "int"
        value: "1"
        

