apiVersion: devices.kubeedge.io/v1beta1
kind: Device
metadata:
  name: temperature-instance

spec:
  deviceModelRef:
    name: temperature-model
  # 协议
  protocol:
    protocolName: modbus
    configData:
      communicateMode: "TCP"   #TCP/RTU
      port: "502"
      slaveID: 1
      ip: "192.168.25.239"   # replace the ip with your imitation device ip
  nodeName: "kind-worker" # replace the nodeName with your edge node name
  #属性
  properties:
    - name: temperature
      desired:
        value: "250"
      visitors:
        protocolName: modbus
        configData:
          dataType: "uint16"
          register: "HoldingRegister"
          offset: 0
          limit: 1
          scale: 1.0 # 温度值的缩放因子
          isSwap: false  # 不交换字节
          isRegisterSwap: false # 不交换寄存器
          Max: 1000
          Min: 0
      collectCycle: 10000
      reportCycle: 10000
      reportToCloud: true
      # 开启推送功能需要部署相关的服务,如broker
      # pushMethod:
      #   mqtt:
      #     topic: "current temperature"
      #     qos: 0
      #     address: "tcp://127.0.0.1:1883"  # replace the address with your mqtt broker address
      #     retained: false
    - name: status
      collectCycle: 10000
      reportCycle: 10000
      reportToCloud: true
      desired:
        value: "1"
      visitors:
        protocolName: modbus
        configData:
          dataType: "uint16"
          register: "CoilRegister"
          offset: 0
          limit: 1
          scale: 1
          isSwap: false
          isRegisterSwap: false
  #方法,可自定义
  methods:
    - name: UpdateStatus
      description: update the status of the device
      propertyNames:
        - status
    - name: GetStatus
      description: get the status of the device
      propertyNames:
        - status
    - name: GetTemperature
      description: get the temperature of the device
      propertyNames:
        - temperature



status:
  twins:
    - propertyName: temperature
      reported:
        metadata:
          timestamp: "1688663455"
          type: "int"
        value: "250"
      observedDesired:
        metadata:
          timestamp: "1688663455"
          type: "int"
        value: "250"
    - propertyName: status
      reported:
        metadata:
          timestamp: "1688663400"
          type: "int"
        value: "1"
      observedDesired:
        metadata:
          timestamp: "1688663400"
          type: "int"
        value: "1"
        

