apiVersion: devices.kubeedge.io/v1beta1
kind: Device
metadata:
  name: temperature-instance
  # labels:
  # description: temperature sensor simulator
  # manufacturer: modbus slave
  # model: AA666
spec:
  deviceModelRef:
    name: temperature-model
  protocol:
    protocolName: modbus
    configData:
      slaveID: 1
      communication:
        mode: tcp
        ip: "192.168.25.239" # replace the ip with your imitation device ip
        port: "502"
  nodeName: kind-worker # replace the nodeName with your edge node name
  properties:
    - name: temperature
      visitors:
        protocolName: modbus
        configData:
          register: HoldingRegister
          offset: 0
          limit: 1
          scale: 1.0 # 温度值的缩放因子
          isSwap: false  # 不交换字节
          isRegisterSwap: false # 不交换寄存器
      collectCycle: 10000
      reportCycle: 10000
      reportToCloud: true
      pushMethod:
        mqtt:
          topic: "current temperature"
          qos: 0
          address: "tcp://127.0.0.1:1883"  # replace the address with your mqtt broker address
          retained: false
    - name: temperature-enable
      desired:
        value: "1"
      visitors:
        protocolName: modbus
        configData:
          register: CoilRegister
          offset: 0
          limit: 1
          scale: 1
          isSwap: false
          isRegisterSwap: false
status:
  twins:
    - propertyName: temperature
      reported:
        metadata:
          timestamp: "1688663455"
          type: "int"
        value: "250"
      observedDesired:
        metadata:
          timestamp: "1688663455"
          type: int
        value: "250"
    - propertyName: temperature-enable
      reported:
        metadata:
          timestamp: "1688663400"
          type: "int"
        value: "1"
      observedDesired:
        metadata:
          timestamp: "1688663400"
          type: int
        value: "1"
        

