apiVersion: devices.kubeedge.io/v1beta1
kind: DeviceInstance
metadata:
  name: temperature-instance
  labels:
  description: temperature sensor simulator
  manufacturer: modbus slave
  model: AA666
spec:
  deviceModelRef:
    name: temperature-model
  protocol:
    protocolName: modbus
    configData:
      slaveID: 1
      communication:
        mode: tcp
        ip: "127.0.0.1"
        port: "502"
  nodeSelector: edge-node
  properties:
    - name: temperature
      visitors:
        protocolName: modbus
        configData:
          register: HoldingRegister
          offset: 0
          limit: 1
          scale: 1.0 # 温度值的缩放因子
          isSwap: false  # 不交换字节
          isRegisterSwap: false # 不交换寄存器
      collectCycle: 10000
      reportCycle: 10000
      reportToCloud: true
      pushMethod:
        mqtt:
          topic: "current temperature"
          qos: 0
          address: "tcp://127.0.0.1:1883"
          retained: false

    - propertyName: temperature-enable
        desired:
          value: "1"
        visitors:
          protocolName: modbus
          configData:
          register: CoilRegister
          offset: 0
          limit: 1
          scale: 1
          isSwap: false
          isRegisterSwap: false
status:
  twins:
    - propertyName: temperature-enable
      reported:
        metadata:
          timestamp: 1688663400
          type: int
        value: 1
      observedDesired:
        metadata:
          timestamp: 1688663400
          type: int
        value: 1
        

